# Generated by Django 3.2.13 on 2022-06-10 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to='image/'),
        ),
    ]
