# Generated by Django 3.2.13 on 2022-06-11 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0002_alter_employee_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employee',
            new_name='Employe',
        ),
    ]
