# Generated by Django 3.2.13 on 2022-06-11 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0003_rename_employee_employe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employe',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='employe',
            old_name='Image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='employe',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='employe',
            old_name='Password',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='employe',
            old_name='Phone',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='employe',
            old_name='Remarks',
            new_name='remarks',
        ),
    ]
