# Generated by Django 3.2.13 on 2022-06-11 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0004_auto_20220611_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='employe',
            name='address',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
